# Application configuration
spring.application.name=restaurant

# Database connection settings (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/restaurant_db
spring.datasource.username=postgres
spring.datasource.password=Mana18

# Hibernate & JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Enable HTML templates hot-swapping for easier development
spring.thymeleaf.cache=false
